import Head from 'next/head';

import ArrowRightIcon from '@mui/icons-material/ArrowRight';
import BedIcon from '@mui/icons-material/Bed';
import HomeIcon from '@mui/icons-material/Home';
import HotelIcon from '@mui/icons-material/Hotel';
import PushPinIcon from '@mui/icons-material/PushPin';

import hotelImage from '@/assets/illustration 5.png';
import { ExploreButtons } from '@/components/ExploreButtons';
import Header from '@/components/Header';
import HeadImage from '@/components/HeadImage';
import IconsMenu from '@/components/IconsMenu';
import Text from '@/components/Text';

export default function Home() {
  return (
    <>
      <Head>
        <title>Travel Tales</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <main>
        <header>
          <Header />
          <HeadImage source={hotelImage} text="Imagem de pessoas viajando" />
        </header>
        <section className="absolute">
          <IconsMenu />
        </section>

        <section className="flex flex-col items-center justify-center w-full mt-[16rem]">
          <Text title text="Hotels" />
          <ExploreButtons.IconStart
            icon={
              <PushPinIcon
                sx={{ color: '#0F9D58', width: '30px', height: '30px' }}
              />
            }
            text="Hotels & Inns around"
          />
          <div className="flex flex-col items-center gap-6 mt-10 mb-20">
            
          </div>
          <ExploreButtons.IconBoth
            iconStart={
              <HotelIcon
                sx={{ width: '40px', height: '40px', marginRight: '5px' }}
              />
            }
            iconEnd={<ArrowRightIcon sx={{ width: '30px', height: '30px' }} />}
            text="https://www.oyorooms.com/"
            link="https://www.oyorooms.com/"
          />
          <ExploreButtons.IconBoth
            iconStart={
              <HomeIcon
                sx={{ width: '40px', height: '40px', marginRight: '5px' }}
              />
            }
            iconEnd={<ArrowRightIcon sx={{ width: '30px', height: '30px' }} />}
            text="https://www.airbnb.co.in/"
            link="https://www.airbnb.co.in/"
          />
          <ExploreButtons.IconBoth
            iconStart={
              <BedIcon
                sx={{ width: '40px', height: '40px', marginRight: '5px' }}
              />
            }
            iconEnd={<ArrowRightIcon sx={{ width: '30px', height: '30px' }} />}
            text="https://www.fabhotels.com/"
            link="https://www.fabhotels.com/"
          />
        </section>
      </main>
    </>
  );
}
