import Head from 'next/head';

import ArrowRightIcon from '@mui/icons-material/ArrowRight';
import DeliveryDiningIcon from '@mui/icons-material/DeliveryDining';
import LocalDiningIcon from '@mui/icons-material/LocalDining';
import LocalPizzaIcon from '@mui/icons-material/LocalPizza';
import RestaurantIcon from '@mui/icons-material/Restaurant';

import foodImage from '@/assets/illustration 6.png';
import { ExploreButtons } from '@/components/ExploreButtons';
import Header from '@/components/Header';
import HeadImage from '@/components/HeadImage';
import IconsMenu from '@/components/IconsMenu';
import Text from '@/components/Text';

export default function Home() {
  return (
    <>
      <Head>
        <title>Travel Tales</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <main>
        <header>
          <Header />
          <HeadImage source={foodImage} text="Imagem de pessoas viajando" />
        </header>
        <section className="absolute">
          <IconsMenu />
        </section>

        <section className="flex flex-col items-center justify-center w-full mt-[17rem]">
          <Text title text="Food" />
          <ExploreButtons.IconStart
            icon={
              <RestaurantIcon
                sx={{ color: '#F4B400', width: '30px', height: '30px' }}
              />
            }
            text="Something to eat"
          />
          <div></div>
          <ExploreButtons.IconBoth
            iconStart={
              <LocalDiningIcon
                sx={{ width: '40px', height: '40px', marginRight: '5px' }}
              />
            }
            iconEnd={<ArrowRightIcon sx={{ width: '30px', height: '30px' }} />}
            text="https://www.zomato.com/"
            link="https://www.zomato.com/"
          />
          <ExploreButtons.IconBoth
            iconStart={
              <DeliveryDiningIcon
                sx={{ width: '40px', height: '40px', marginRight: '5px' }}
              />
            }
            iconEnd={<ArrowRightIcon sx={{ width: '30px', height: '30px' }} />}
            text="https://www.swiggy.com/"
            link="https://www.swiggy.com/"
          />
          <ExploreButtons.IconBoth
            iconStart={
              <LocalPizzaIcon
                sx={{ width: '40px', height: '40px', marginRight: '5px' }}
              />
            }
            iconEnd={<ArrowRightIcon sx={{ width: '30px', height: '30px' }} />}
            text="https://www.doordash.com/"
            link="https://www.doordash.com/"
          />
        </section>
      </main>
    </>
  );
}
